[2022-03-23 05:21:00,177] {processor.py:163} INFO - Started process (PID=154) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:21:00,178] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:21:00,178] {logging_mixin.py:109} INFO - [2022-03-23 05:21:00,178] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:21:00,182] {logging_mixin.py:109} INFO - [2022-03-23 05:21:00,180] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:21:00,192] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:21:00,391] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.218 seconds
[2022-03-23 05:22:34,818] {processor.py:163} INFO - Started process (PID=195) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:22:34,837] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:22:34,837] {logging_mixin.py:109} INFO - [2022-03-23 05:22:34,837] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:22:34,840] {logging_mixin.py:109} INFO - [2022-03-23 05:22:34,839] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:22:34,848] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:22:36,635] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.820 seconds
[2022-03-23 05:23:36,632] {processor.py:163} INFO - Started process (PID=218) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:23:37,242] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:23:37,243] {logging_mixin.py:109} INFO - [2022-03-23 05:23:37,243] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:23:37,247] {logging_mixin.py:109} INFO - [2022-03-23 05:23:37,245] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:23:37,255] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:23:37,510] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.880 seconds
[2022-03-23 05:24:26,470] {processor.py:163} INFO - Started process (PID=242) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:24:26,482] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:24:26,482] {logging_mixin.py:109} INFO - [2022-03-23 05:24:26,482] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:24:26,484] {logging_mixin.py:109} INFO - [2022-03-23 05:24:26,484] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:24:26,492] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:24:26,687] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.220 seconds
[2022-03-23 05:25:10,399] {processor.py:163} INFO - Started process (PID=337) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:25:10,566] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:25:10,567] {logging_mixin.py:109} INFO - [2022-03-23 05:25:10,567] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:25:10,571] {logging_mixin.py:109} INFO - [2022-03-23 05:25:10,570] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:25:10,580] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:25:10,744] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.346 seconds
[2022-03-23 05:25:55,251] {processor.py:163} INFO - Started process (PID=363) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:25:55,262] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:25:55,262] {logging_mixin.py:109} INFO - [2022-03-23 05:25:55,262] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:25:55,264] {logging_mixin.py:109} INFO - [2022-03-23 05:25:55,264] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:25:55,272] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:25:55,692] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.444 seconds
[2022-03-23 05:26:41,369] {processor.py:163} INFO - Started process (PID=384) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:26:41,417] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:26:41,418] {logging_mixin.py:109} INFO - [2022-03-23 05:26:41,418] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:26:41,421] {logging_mixin.py:109} INFO - [2022-03-23 05:26:41,420] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:26:41,431] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:26:41,767] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.400 seconds
[2022-03-23 05:27:23,890] {processor.py:163} INFO - Started process (PID=409) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:27:23,911] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:27:23,912] {logging_mixin.py:109} INFO - [2022-03-23 05:27:23,912] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:27:23,914] {logging_mixin.py:109} INFO - [2022-03-23 05:27:23,914] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:27:24,154] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:27:24,300] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.413 seconds
[2022-03-23 05:28:13,986] {processor.py:163} INFO - Started process (PID=430) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:28:13,990] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:28:13,990] {logging_mixin.py:109} INFO - [2022-03-23 05:28:13,990] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:28:13,997] {logging_mixin.py:109} INFO - [2022-03-23 05:28:13,995] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:28:14,008] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:28:14,449] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.466 seconds
[2022-03-23 05:28:50,960] {processor.py:163} INFO - Started process (PID=454) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:28:50,984] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:28:50,988] {logging_mixin.py:109} INFO - [2022-03-23 05:28:50,988] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:28:50,991] {logging_mixin.py:109} INFO - [2022-03-23 05:28:50,990] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:28:51,023] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:28:51,431] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.483 seconds
[2022-03-23 05:30:02,815] {processor.py:163} INFO - Started process (PID=496) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:30:03,018] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:30:03,019] {logging_mixin.py:109} INFO - [2022-03-23 05:30:03,018] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:30:03,022] {logging_mixin.py:109} INFO - [2022-03-23 05:30:03,021] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:30:03,033] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:30:03,442] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.628 seconds
[2022-03-23 05:30:49,545] {processor.py:163} INFO - Started process (PID=516) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:30:50,099] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:30:50,100] {logging_mixin.py:109} INFO - [2022-03-23 05:30:50,100] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:30:50,103] {logging_mixin.py:109} INFO - [2022-03-23 05:30:50,102] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:30:50,113] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:30:50,292] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.752 seconds
[2022-03-23 05:31:41,940] {processor.py:163} INFO - Started process (PID=541) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:31:43,482] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:31:43,483] {logging_mixin.py:109} INFO - [2022-03-23 05:31:43,483] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:31:43,486] {logging_mixin.py:109} INFO - [2022-03-23 05:31:43,486] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:31:43,677] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:31:43,821] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.883 seconds
[2022-03-23 05:32:24,743] {processor.py:163} INFO - Started process (PID=561) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:32:24,760] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:32:24,761] {logging_mixin.py:109} INFO - [2022-03-23 05:32:24,761] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:32:24,765] {logging_mixin.py:109} INFO - [2022-03-23 05:32:24,764] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:32:24,773] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:32:24,930] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.190 seconds
[2022-03-23 05:33:09,270] {processor.py:163} INFO - Started process (PID=582) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:33:09,288] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:33:09,288] {logging_mixin.py:109} INFO - [2022-03-23 05:33:09,288] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:33:09,291] {logging_mixin.py:109} INFO - [2022-03-23 05:33:09,290] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:33:09,299] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:33:09,475] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.208 seconds
[2022-03-23 05:33:59,056] {processor.py:163} INFO - Started process (PID=605) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:33:59,153] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:33:59,154] {logging_mixin.py:109} INFO - [2022-03-23 05:33:59,154] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:33:59,157] {logging_mixin.py:109} INFO - [2022-03-23 05:33:59,156] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:33:59,168] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:34:00,572] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.518 seconds
[2022-03-23 05:34:47,365] {processor.py:163} INFO - Started process (PID=627) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:34:47,375] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:34:47,376] {logging_mixin.py:109} INFO - [2022-03-23 05:34:47,376] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:34:47,380] {logging_mixin.py:109} INFO - [2022-03-23 05:34:47,379] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:34:47,393] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:34:49,158] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.796 seconds
[2022-03-23 05:35:30,106] {processor.py:163} INFO - Started process (PID=648) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:35:30,128] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:35:30,129] {logging_mixin.py:109} INFO - [2022-03-23 05:35:30,128] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:35:30,132] {logging_mixin.py:109} INFO - [2022-03-23 05:35:30,131] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:35:30,140] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:35:31,731] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.628 seconds
[2022-03-23 05:36:14,908] {processor.py:163} INFO - Started process (PID=668) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:36:15,077] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:36:15,080] {logging_mixin.py:109} INFO - [2022-03-23 05:36:15,080] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:36:15,083] {logging_mixin.py:109} INFO - [2022-03-23 05:36:15,082] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:36:15,823] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:36:16,020] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.115 seconds
[2022-03-23 05:37:10,412] {processor.py:163} INFO - Started process (PID=691) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:37:10,441] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:37:10,442] {logging_mixin.py:109} INFO - [2022-03-23 05:37:10,442] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:37:10,445] {logging_mixin.py:109} INFO - [2022-03-23 05:37:10,444] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 4, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres'
[2022-03-23 05:37:10,454] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:37:11,151] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.742 seconds
[2022-03-23 05:38:04,175] {processor.py:163} INFO - Started process (PID=722) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:38:04,989] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:38:04,990] {logging_mixin.py:109} INFO - [2022-03-23 05:38:04,990] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:38:05,279] {logging_mixin.py:109} INFO - [2022-03-23 05:38:05,279] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 72, in <module>
    schedule_interval=timedelta(days=1),
NameError: name 'timedelta' is not defined
[2022-03-23 05:38:05,287] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:38:05,487] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.316 seconds
[2022-03-23 05:40:09,931] {processor.py:163} INFO - Started process (PID=748) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:40:10,002] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:40:10,004] {logging_mixin.py:109} INFO - [2022-03-23 05:40:10,004] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:40:10,197] {logging_mixin.py:109} INFO - [2022-03-23 05:40:10,196] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 72, in <module>
    schedule_interval=timedelta(days=1),
NameError: name 'timedelta' is not defined
[2022-03-23 05:40:10,534] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:40:10,891] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.963 seconds
[2022-03-23 05:41:30,491] {processor.py:163} INFO - Started process (PID=790) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:41:30,502] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:41:30,502] {logging_mixin.py:109} INFO - [2022-03-23 05:41:30,502] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:41:30,688] {logging_mixin.py:109} INFO - [2022-03-23 05:41:30,688] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 72, in <module>
    schedule_interval=timedelta(days=1),
NameError: name 'timedelta' is not defined
[2022-03-23 05:41:30,695] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:41:30,839] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.351 seconds
[2022-03-23 05:42:20,400] {processor.py:163} INFO - Started process (PID=819) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:42:20,459] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:42:20,460] {logging_mixin.py:109} INFO - [2022-03-23 05:42:20,460] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:42:20,632] {logging_mixin.py:109} INFO - [2022-03-23 05:42:20,631] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 72, in <module>
    schedule_interval=timedelta(days=1),
NameError: name 'timedelta' is not defined
[2022-03-23 05:42:21,874] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:42:22,015] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.618 seconds
[2022-03-23 05:43:04,910] {processor.py:163} INFO - Started process (PID=851) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:43:04,920] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:43:04,921] {logging_mixin.py:109} INFO - [2022-03-23 05:43:04,921] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:43:05,082] {logging_mixin.py:109} INFO - [2022-03-23 05:43:05,082] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 72, in <module>
    schedule_interval=timedelta(days=1),
NameError: name 'timedelta' is not defined
[2022-03-23 05:43:05,087] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:43:06,681] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.773 seconds
[2022-03-23 05:43:42,538] {processor.py:163} INFO - Started process (PID=870) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:43:43,217] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:43:43,218] {logging_mixin.py:109} INFO - [2022-03-23 05:43:43,218] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:43:43,400] {logging_mixin.py:109} INFO - [2022-03-23 05:43:43,399] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 76, in <module>
    get_data_cine >> get_data_uba
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2022-03-23 05:43:43,409] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:43:43,552] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.016 seconds
[2022-03-23 05:44:22,690] {processor.py:163} INFO - Started process (PID=891) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:44:23,059] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:44:23,060] {logging_mixin.py:109} INFO - [2022-03-23 05:44:23,060] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:44:23,242] {logging_mixin.py:109} INFO - [2022-03-23 05:44:23,242] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 76, in <module>
    get_data_cine >> get_data_uba
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2022-03-23 05:44:23,354] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:44:23,556] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.869 seconds
[2022-03-23 05:45:04,210] {processor.py:163} INFO - Started process (PID=911) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:45:04,614] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:45:04,615] {logging_mixin.py:109} INFO - [2022-03-23 05:45:04,615] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:45:04,792] {logging_mixin.py:109} INFO - [2022-03-23 05:45:04,791] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 76, in <module>
    get_data_cine >> get_data_uba
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2022-03-23 05:45:04,798] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:45:04,977] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.770 seconds
[2022-03-23 05:45:50,016] {processor.py:163} INFO - Started process (PID=931) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:45:50,082] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:45:50,082] {logging_mixin.py:109} INFO - [2022-03-23 05:45:50,082] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:45:50,286] {logging_mixin.py:109} INFO - [2022-03-23 05:45:50,285] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 76, in <module>
    get_data_cine >> get_data_uba
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2022-03-23 05:45:50,291] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:45:51,184] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.171 seconds
[2022-03-23 05:46:46,487] {processor.py:163} INFO - Started process (PID=954) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:46:46,576] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:46:46,577] {logging_mixin.py:109} INFO - [2022-03-23 05:46:46,576] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:46:46,807] {logging_mixin.py:109} INFO - [2022-03-23 05:46:46,806] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 76, in <module>
    get_data_cine >> get_data_uba
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2022-03-23 05:46:46,814] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:46:47,026] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.542 seconds
[2022-03-23 05:47:37,975] {processor.py:163} INFO - Started process (PID=977) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:47:38,038] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:47:38,038] {logging_mixin.py:109} INFO - [2022-03-23 05:47:38,038] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:47:38,236] {logging_mixin.py:109} INFO - [2022-03-23 05:47:38,235] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 76, in <module>
    get_data_cine >> get_data_uba
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2022-03-23 05:47:38,242] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:47:39,110] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.137 seconds
[2022-03-23 05:48:19,467] {processor.py:163} INFO - Started process (PID=998) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:48:19,469] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:48:19,470] {logging_mixin.py:109} INFO - [2022-03-23 05:48:19,470] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:48:19,628] {logging_mixin.py:109} INFO - [2022-03-23 05:48:19,628] {dagbag.py:334} ERROR - Failed to import: /home/lowenhard/airflow/dags/postgres_conn.py
Traceback (most recent call last):
  File "/home/lowenhard/acceleration/env/lib/python3.8/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lowenhard/airflow/dags/postgres_conn.py", line 76, in <module>
    get_data_cine >> get_data_uba
TypeError: unsupported operand type(s) for >>: 'function' and 'function'
[2022-03-23 05:48:19,635] {processor.py:656} WARNING - No viable dags retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:48:19,791] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.328 seconds
[2022-03-23 05:49:05,912] {processor.py:163} INFO - Started process (PID=1019) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:49:06,084] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:49:06,085] {logging_mixin.py:109} INFO - [2022-03-23 05:49:06,085] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:49:06,290] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:49:07,761] {logging_mixin.py:109} INFO - [2022-03-23 05:49:07,760] {manager.py:496} INFO - Created Permission View: can read on DAG:postgres_dag
[2022-03-23 05:49:07,964] {logging_mixin.py:109} INFO - [2022-03-23 05:49:07,964] {manager.py:496} INFO - Created Permission View: can edit on DAG:postgres_dag
[2022-03-23 05:49:07,965] {logging_mixin.py:109} INFO - [2022-03-23 05:49:07,965] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:49:07,976] {logging_mixin.py:109} INFO - [2022-03-23 05:49:07,976] {dag.py:2417} INFO - Creating ORM DAG for postgres_dag
[2022-03-23 05:49:07,985] {logging_mixin.py:109} INFO - [2022-03-23 05:49:07,985] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:49:08,530] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 2.620 seconds
[2022-03-23 05:49:29,370] {processor.py:163} INFO - Started process (PID=1037) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:49:29,370] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:49:29,371] {logging_mixin.py:109} INFO - [2022-03-23 05:49:29,371] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:49:29,627] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:49:29,633] {logging_mixin.py:109} INFO - [2022-03-23 05:49:29,633] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:49:29,646] {logging_mixin.py:109} INFO - [2022-03-23 05:49:29,646] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:49:30,916] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.549 seconds
[2022-03-23 05:50:50,311] {processor.py:163} INFO - Started process (PID=1078) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:50:50,332] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:50:50,334] {logging_mixin.py:109} INFO - [2022-03-23 05:50:50,333] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:50:50,658] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:50:50,669] {logging_mixin.py:109} INFO - [2022-03-23 05:50:50,669] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:50:50,685] {logging_mixin.py:109} INFO - [2022-03-23 05:50:50,685] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:50:51,494] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.187 seconds
[2022-03-23 05:51:44,221] {processor.py:163} INFO - Started process (PID=1100) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:51:45,526] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:51:45,527] {logging_mixin.py:109} INFO - [2022-03-23 05:51:45,527] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:51:45,864] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:51:45,875] {logging_mixin.py:109} INFO - [2022-03-23 05:51:45,875] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:51:45,892] {logging_mixin.py:109} INFO - [2022-03-23 05:51:45,892] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:51:46,525] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 2.308 seconds
[2022-03-23 05:52:49,197] {processor.py:163} INFO - Started process (PID=1124) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:52:49,215] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:52:49,215] {logging_mixin.py:109} INFO - [2022-03-23 05:52:49,215] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:52:49,381] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:52:49,388] {logging_mixin.py:109} INFO - [2022-03-23 05:52:49,388] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:52:49,397] {logging_mixin.py:109} INFO - [2022-03-23 05:52:49,397] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:52:49,669] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.475 seconds
[2022-03-23 05:53:42,451] {processor.py:163} INFO - Started process (PID=1147) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:53:43,530] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:53:43,531] {logging_mixin.py:109} INFO - [2022-03-23 05:53:43,530] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:53:43,788] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:53:43,798] {logging_mixin.py:109} INFO - [2022-03-23 05:53:43,798] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:53:43,810] {logging_mixin.py:109} INFO - [2022-03-23 05:53:43,810] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:53:43,984] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.536 seconds
[2022-03-23 05:54:28,022] {processor.py:163} INFO - Started process (PID=1171) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:54:28,240] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:54:28,241] {logging_mixin.py:109} INFO - [2022-03-23 05:54:28,241] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:54:28,442] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:54:28,450] {logging_mixin.py:109} INFO - [2022-03-23 05:54:28,450] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:54:28,527] {logging_mixin.py:109} INFO - [2022-03-23 05:54:28,527] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:54:30,304] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 2.285 seconds
[2022-03-23 05:55:35,208] {processor.py:163} INFO - Started process (PID=1195) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:55:35,307] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:55:35,307] {logging_mixin.py:109} INFO - [2022-03-23 05:55:35,307] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:55:35,521] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:55:35,529] {logging_mixin.py:109} INFO - [2022-03-23 05:55:35,529] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:55:35,613] {logging_mixin.py:109} INFO - [2022-03-23 05:55:35,613] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:55:36,161] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.956 seconds
[2022-03-23 05:56:21,013] {processor.py:163} INFO - Started process (PID=1218) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:56:21,215] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:56:21,216] {logging_mixin.py:109} INFO - [2022-03-23 05:56:21,216] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:56:21,411] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:56:21,420] {logging_mixin.py:109} INFO - [2022-03-23 05:56:21,420] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:56:21,497] {logging_mixin.py:109} INFO - [2022-03-23 05:56:21,496] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:56:23,157] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 2.147 seconds
[2022-03-23 05:57:09,142] {processor.py:163} INFO - Started process (PID=1238) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:57:09,195] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:57:09,196] {logging_mixin.py:109} INFO - [2022-03-23 05:57:09,195] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:57:09,394] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:57:09,402] {logging_mixin.py:109} INFO - [2022-03-23 05:57:09,402] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:57:09,481] {logging_mixin.py:109} INFO - [2022-03-23 05:57:09,481] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:57:10,170] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.030 seconds
[2022-03-23 05:57:50,942] {processor.py:163} INFO - Started process (PID=1260) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:57:51,633] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:57:51,634] {logging_mixin.py:109} INFO - [2022-03-23 05:57:51,634] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:57:52,152] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:57:52,160] {logging_mixin.py:109} INFO - [2022-03-23 05:57:52,160] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:57:52,235] {logging_mixin.py:109} INFO - [2022-03-23 05:57:52,235] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:57:52,382] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.444 seconds
[2022-03-23 05:58:34,750] {processor.py:163} INFO - Started process (PID=1280) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:58:34,754] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:58:34,755] {logging_mixin.py:109} INFO - [2022-03-23 05:58:34,755] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:58:34,936] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:58:35,016] {logging_mixin.py:109} INFO - [2022-03-23 05:58:35,016] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:58:35,026] {logging_mixin.py:109} INFO - [2022-03-23 05:58:35,026] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:58:37,450] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 2.702 seconds
[2022-03-23 05:59:25,058] {processor.py:163} INFO - Started process (PID=1300) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:59:25,151] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 05:59:25,153] {logging_mixin.py:109} INFO - [2022-03-23 05:59:25,153] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:59:25,430] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 05:59:25,437] {logging_mixin.py:109} INFO - [2022-03-23 05:59:25,436] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 05:59:25,445] {logging_mixin.py:109} INFO - [2022-03-23 05:59:25,445] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 05:59:25,619] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 0.563 seconds
[2022-03-23 06:00:11,070] {processor.py:163} INFO - Started process (PID=1322) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:00:11,078] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 06:00:11,079] {logging_mixin.py:109} INFO - [2022-03-23 06:00:11,079] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:00:11,317] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:00:11,325] {logging_mixin.py:109} INFO - [2022-03-23 06:00:11,325] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 06:00:11,342] {logging_mixin.py:109} INFO - [2022-03-23 06:00:11,342] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 06:00:12,878] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.810 seconds
[2022-03-23 06:00:55,480] {processor.py:163} INFO - Started process (PID=1344) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:00:55,482] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 06:00:55,483] {logging_mixin.py:109} INFO - [2022-03-23 06:00:55,483] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:00:55,918] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:00:55,929] {logging_mixin.py:109} INFO - [2022-03-23 06:00:55,928] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 06:00:55,948] {logging_mixin.py:109} INFO - [2022-03-23 06:00:55,948] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 06:00:57,033] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.556 seconds
[2022-03-23 06:01:40,895] {processor.py:163} INFO - Started process (PID=1364) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:01:41,019] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 06:01:41,020] {logging_mixin.py:109} INFO - [2022-03-23 06:01:41,020] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:01:41,276] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:01:41,282] {logging_mixin.py:109} INFO - [2022-03-23 06:01:41,282] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 06:01:41,290] {logging_mixin.py:109} INFO - [2022-03-23 06:01:41,290] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 06:01:42,180] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.286 seconds
[2022-03-23 06:02:28,063] {processor.py:163} INFO - Started process (PID=1386) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:02:28,088] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 06:02:28,089] {logging_mixin.py:109} INFO - [2022-03-23 06:02:28,088] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:02:28,336] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:02:28,344] {logging_mixin.py:109} INFO - [2022-03-23 06:02:28,344] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 06:02:28,355] {logging_mixin.py:109} INFO - [2022-03-23 06:02:28,354] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 06:02:29,126] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.066 seconds
[2022-03-23 06:03:08,507] {processor.py:163} INFO - Started process (PID=1407) to work on /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:03:08,530] {processor.py:642} INFO - Processing file /home/lowenhard/airflow/dags/postgres_conn.py for tasks to queue
[2022-03-23 06:03:08,531] {logging_mixin.py:109} INFO - [2022-03-23 06:03:08,531] {dagbag.py:500} INFO - Filling up the DagBag from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:03:08,778] {processor.py:654} INFO - DAG(s) dict_keys(['postgres_dag']) retrieved from /home/lowenhard/airflow/dags/postgres_conn.py
[2022-03-23 06:03:08,784] {logging_mixin.py:109} INFO - [2022-03-23 06:03:08,784] {dag.py:2398} INFO - Sync 1 DAGs
[2022-03-23 06:03:08,795] {logging_mixin.py:109} INFO - [2022-03-23 06:03:08,795] {dag.py:2937} INFO - Setting next_dagrun for postgres_dag to 2022-03-23T00:00:00+00:00
[2022-03-23 06:03:09,989] {processor.py:171} INFO - Processing /home/lowenhard/airflow/dags/postgres_conn.py took 1.484 seconds
